#!/usr/bin/env bash

# Dasharo Configuration Utility Container

SCRIPT_DIR=$(dirname "$(readlink -f ${BASH_SOURCE[0]})")

DOCKER_IMAGE="ghcr.io/dasharo/dasharo-sdk:v1.5.0"

# Initialize an array to store Docker arguments
DOCKER_ARGS=()

# Initialize an array to store the command to be executed in the container
COMMAND_ARGS=()

# Function to add a bind mount for a file
add_bind_mount() {
    local FILE_PATH=$1
    local ABS_PATH
    ABS_PATH=$(realpath "$FILE_PATH")
    FILENAME="$(basename "$ABS_PATH")"
    DOCKER_ARGS+=( '-v' "$ABS_PATH":/"${FILENAME}" )
}

# Iterate over the command line arguments
for ARG in "$@"; do
    if [[ -f "$ARG" ]]; then
        if [[ -v CI ]]; then
            COMMAND_ARGS+=("$(realpath "$ARG")")
        else
            # Convert the file path to an absolute path and add a bind mount
            add_bind_mount "$ARG"
            COMMAND_ARGS+=("/$FILENAME")
        fi
    else
        COMMAND_ARGS+=("$ARG")
    fi
done

if [[ -v CI ]]; then
    ../dcu "${COMMAND_ARGS[@]}"
else
    docker run -t --rm -v "${SCRIPT_DIR}:${SCRIPT_DIR}" "${DOCKER_ARGS[@]}" -w "${SCRIPT_DIR}" $DOCKER_IMAGE ./dcu "${COMMAND_ARGS[@]}"
fi
