version: '3'

includes:
  docker:
    taskfile: https://raw.githubusercontent.com/3mdeb/taskfiles/refs/heads/main/docker.yml
    checksum: 4cc693f1146f1d93a4b3552b267c2f8e35b07ed7235fbeded5c686d61a15c4e6

tasks:
  build:
    desc: Generate CLI using bashly
    cmds:
      - task: docker:run
        vars:
          IMAGE: dannyben/bashly:1.3.6
          VOLUMES: "{{.PWD}}:/app"
          WORKDIR: /app
          COMMAND: bashly generate
          DOCKER_USER:
            sh: echo "$(id -u):$(id -g)"

  test:
    desc: Run approval tests
    deps: [build]
    cmds:
      - task: docker:run
        vars:
          IMAGE: ghcr.io/dasharo/dasharo-sdk:v1.9.2
          VOLUMES: "{{.PWD}}:/dcu"
          WORKDIR: /dcu
          COMMAND: test/approve-ci
          DOCKER_USER:
            sh: echo "$(id -u):$(id -g)"
